# https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    versioning-strategy: widen
    target-branch: "master"
    directory: "/"
    labels:
      - "dependabot"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "deps(auto): "
      include: "scope"

