/* Autogenerated Index [Types, Types-Namespaced] */

export * from "./some_interface.js"
export * as some_interface from "./some_interface.js"
export * from "./some_type.js"
export * as some_type from "./some_type.js"
