/* Autogenerated Index [Default] */

import { named } from "./some_named.js"
import named_default from "./some_default_named.js"
import some_default from "./some_default.js"
import some_default_class from "./some_default_class.js"
import { some_function } from "./some_function.js"
import { some_function_w_generics } from "./some_function_w_generics.js"
import { some_named_w_types } from "./some_named_w_types.js"
import { SomeClass } from "./some_class.js"
import SomeClassNamed from "./some_default_named_class.js"
import { SomeClassWGenerics } from "./some_class_w_generics.js"

export default {
	named,
	named_default,
	some_default,
	some_default_class,
	some_function,
	some_function_w_generics,
	some_named_w_types,
	SomeClass,
	SomeClassNamed,
	SomeClassWGenerics,
}
