// @ts-nocheck
/**
 * Some Comment
 */
/**
 * Some Other Comment
 */
// Some Other Other Comment

export const here = "should be ignored";

/* Autogenerated Index [Named, Types] */

export { default as folder_default } from "./folder_default/index.js"
export { default as folder_manual_default } from "./folder_manual_default/index.js"
export * as folder_manual_named from "./folder_manual_named/index.js"
export * as folder_manual_named_re_export from "./folder_manual_named_re_export/index.js"
export * as folder_named from "./folder_named/index.js"
export * as folder_named_unwrapped from "./folder_named_unwrapped/index.js"
export { named } from "./some_named.js"
export { default as named_default } from "./some_default_named.js"
export { default as some_default } from "./some_default.js"
export { default as some_default_class } from "./some_default_class.js"
export { some_function } from "./some_function.js"
export { some_function_w_generics } from "./some_function_w_generics.js"
export { some_named_w_types } from "./some_named_w_types.js"
export { SomeClass } from "./some_class.js"
export { default as SomeClassNamed } from "./some_default_named_class.js"
export { SomeClassWGenerics } from "./some_class_w_generics.js"

export * from "./folder_types/index.js"
export * from "./folder_types_both/index.js"
export * from "./folder_types_namespaced/index.js"
export * from "./some_interface.js"
export * from "./some_type.js"
