/* Autogenerated Index [Default] */

import { named } from "./some_named"
import named_default from "./some_default_named"
import some_default from "./some_default"
import some_default_class from "./some_default_class"
import { some_function } from "./some_function"
import { some_function_w_generics } from "./some_function_w_generics"
import { SomeClass } from "./some_class"
import SomeClassNamed from "./some_default_named_class"
import { SomeClassWGenerics } from "./some_class_w_generics"

export default {
	named,
	named_default,
	some_default,
	some_default_class,
	some_function,
	some_function_w_generics,
	SomeClass,
	SomeClassNamed,
	SomeClassWGenerics,
}
