// @ts-nocheck
/**
 * Some Comment
 */
/**
 * Some Other Comment
 */
// Some Other Other Comment

export const here = "should be ignored";

/* Autogenerated Index [Named, Types] */

export { default as folder_default } from "./folder_default"
export { default as folder_manual_default } from "./folder_manual_default"
export * as folder_manual_named from "./folder_manual_named"
export * as folder_manual_named_re_export from "./folder_manual_named_re_export"
export * as folder_named from "./folder_named"
export * as folder_named_unwrapped from "./folder_named_unwrapped"
export { named } from "./some_named"
export { default as named_default } from "./some_default_named"
export { default as some_default } from "./some_default"
export { default as some_default_class } from "./some_default_class"
export { some_function } from "./some_function"
export { some_function_w_generics } from "./some_function_w_generics"
export { some_named_w_types } from "./some_named_w_types"
export { SomeClass } from "./some_class"
export { default as SomeClassNamed } from "./some_default_named_class"
export { SomeClassWGenerics } from "./some_class_w_generics"

export * from "./folder_types"
export * from "./folder_types_both"
export * from "./folder_types_namespaced"
export * from "./some_interface"
export * from "./some_type"
