// @ts-nocheck
/**
 * Some Comment
 */
/**
 * Some Other Comment
 */
// Some Other Other Comment

export const here = "should be ignored";

/* Autogenerated Index [Named, Types] */

import * as _folder_named from "./folder_named"
export const folder_named = _folder_named
