/* Autogenerated Index [Types, Types-Namespaced] */

export * from "./some_interface"
export * as some_interface from "./some_interface"
export * from "./some_type"
export * as some_type from "./some_type"
